version: '2'
services:
  web:
    image: phundament/nginx-one:1.9-5.1.1
    environment:
      - FASTCGI_PASS_HOST=php
    ports:
      - '8100:80'
      - '8200:8080'
    volumes:
      # Application testing
      - ./app/web:/app/web
      - ./nginx/conf.d:/etc/nginx/conf.d
